name: Android CI/Build

on:
  push:
    branches: [ "prod" ]
    tags:
      - 'version*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build APK
      run: ./gradlew assembleRelease
    - name: Save APK
      run: |
        mkdir app_apk
        mv app/build/outputs/apk/release/app-release.apk app_apk/
    - name: Create Release
      uses: actions/create-release@v1
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
        body: 'Release APK'
        draft: false
        prerelease: true
        files: app_apk/app-release.apk
